LOCAL_PATH := $(call my-dir)

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a

TARGET_BOARD_PLATFORM := mt6855

BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4

BOARD_PAGE_SIZE := 4096

BOARD_BOOTIMAGE_PARTITION_SIZE := 134217728
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 8388608
BOARD_DTBOIMG_PARTITION_SIZE := 8388608

BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true

BOARD_KERNEL_PAGESIZE := 4096

BOARD_USES_RECOVERY_AS_BOOT := false

BOARD_BUILD_SYSTEM_ROOT_IMAGE := false

BOARD_FLASH_BLOCK_SIZE := 131072

# A/B
AB_OTA_UPDATER := true
TARGET_NO_RECOVERY := true

# Dynamic partitions
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := xiaomi_dynamic_partitions
BOARD_XIAOMI_DYNAMIC_PARTITIONS_SIZE := 9110026240
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST := \
    system \
    system_ext \
    product \
    vendor \
    system_dlkm \
    vendor_dlkm \
    odm_dlkm

# OrangeFox vendor_boot recovery
ifeq ($(FOX_VENDOR_BOOT_RECOVERY),1)
    BOARD_BOOT_HEADER_VERSION := 4
    BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
endif
