LOCAL_PATH := $(call my-dir)

TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_VARIANT := generic

TARGET_BOARD_PLATFORM := mt6855

# Android boot image / vendor_boot HDR4
BOARD_BOOT_HEADER_VERSION := 4
BOARD_VENDOR_BOOT_HEADER_VERSION := 4
BOARD_PAGE_SIZE := 4096
BOARD_KERNEL_PAGESIZE := 4096

BOARD_BOOTIMAGE_PARTITION_SIZE := 134217728
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_INIT_BOOT_IMAGE_PARTITION_SIZE := 8388608
BOARD_DTBOIMG_PARTITION_SIZE := 8388608

BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
BOARD_BUILD_SYSTEM_ROOT_IMAGE := false
BOARD_USES_RECOVERY_AS_BOOT := false
TARGET_NO_RECOVERY := true

# A/B + Virtual A/B
AB_OTA_UPDATER := true
AB_OTA_PARTITIONS := system system_ext product vendor vendor_dlkm odm_dlkm system_dlkm vbmeta_system vbmeta_vendor boot
BOARD_VNDK_VERSION := current

# Dynamic partitions
PRODUCT_USE_DYNAMIC_PARTITIONS := true
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := xiaomi_dynamic_partitions
BOARD_XIAOMI_DYNAMIC_PARTITIONS_SIZE := 9122611200
BOARD_XIAOMI_DYNAMIC_PARTITIONS_PARTITION_LIST :=     system     system_ext     product     vendor     mi_ext     system_dlkm     vendor_dlkm     odm_dlkm

BOARD_FLASH_BLOCK_SIZE := 131072

# Recovery UI / filesystems
TARGET_RECOVERY_PIXEL_FORMAT := BGRA_8888
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

# OrangeFox vendor_boot recovery is enabled from vendorsetup.sh.
ifeq ($(FOX_VENDOR_BOOT_RECOVERY),1)
    BOARD_BOOT_HEADER_VERSION := 4
    BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT := true
endif
