export FOX_BUILD_DEVICE=beryl
export FOX_AB_DEVICE=1
export FOX_VIRTUAL_AB_DEVICE=1
export FOX_VENDOR_BOOT_RECOVERY=1
export FOX_INSTALLER_VENDOR_BOOT_RAMDISK_INSTALL=1
export FOX_VANILLA_BUILD=1
export FOX_USE_BASH_SHELL=1
export FOX_USE_NANO_EDITOR=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_LZ4_BINARY=1
export FOX_ADD_API_V36_PREBUILTS=1
export OF_USE_AIDL_BOOT_CONTROL=1

# export FOX_REFERENCE_VENDOR_BOOT_IMAGE=$(LOCAL_PATH)/prebuilt/vendor_boot.img
# export OF_FORCE_USE_RECOVERY_FSTAB=1
# export OF_VAB_ORS_WIPE_DATA_IS_FORMAT=1
