# POCO M7 Pro 5G (beryl)
# Stock Android 16 / API 36
# MT6855

# Core system:
# /system/bin/vold
# /system/bin/keystore2
# /system/bin/gatekeeperd
# /system/bin/vold_prepare_subdirs
# /system/bin/recovery-persist
# /system/bin/recovery-refresh
# /system/bin/uncrypt

# Vendor security:
# /vendor/bin/tee
# /vendor/bin/tee-supplicant
# /vendor/bin/hw/android.hardware.security.keymint@4.0-service.mitee
# /vendor/bin/hw/android.hardware.gatekeeper-service.mitee

# TEE:
# /vendor/mitee/

# FBE:
# Android FBE v2
# fscrypt
# AES-256-XTS contents encryption
# AES-256-CTS filename encryption
# metadata encryption
# wrapped-key support
